package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Check Rewards card eligibility")
    void generatedTest() {
        step("Open 'https://www.barclays.co.uk/credit-cards/check-your-eligibility/'", () -> {
            step("// todo: just add selenium action");
        });

        step("Click href=\"/credit-cards/reward-cards/barclays-rewards/?\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Click Check your eligibility", () -> {
            step("// todo: just add selenium action");
        });

        step("Verify there is text Confirm your eligibility for this card", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.barclays.co.uk/credit-cards/check-your-eligibility/'", () ->
            open("https://www.barclays.co.uk/credit-cards/check-your-eligibility/"));

        step("Page title should have text 'Credit card eligibility checker | Barclays'", () -> {
            String expectedTitle = "Credit card eligibility checker | Barclays";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.barclays.co.uk/credit-cards/check-your-eligibility/'", () ->
            open("https://www.barclays.co.uk/credit-cards/check-your-eligibility/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}